version: "3.5"

volumes:
  postgres_data:

networks:
  pic_api_docker_network:
    name: pic_api_docker_network
    driver: bridge

services:

  app:
    # To pass constants from .env during build
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    # Tiers have to be created before superuser/user - sequence matters here.
    command: >
      sh -c "python manage.py wait_for_db && python manage.py migrate && python manage.py create_default_tiers && python manage.py create_superuser_if_not_exists && python manage.py create_regular_user_if_not_exists && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - pic_api_docker_network

  db:
    build:
      context: .
      dockerfile: build/Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - pic_api_docker_network
