# Generated by Django 3.2.6 on 2023-02-16 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic', max_length=100)),
                ('thumbnail_small', models.BooleanField(default=True)),
                ('thumbnail_large', models.BooleanField(default=False)),
                ('image_link', models.BooleanField(default=False)),
                ('expiring_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail_small', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_large', models.CharField(blank=True, max_length=255, null=True)),
                ('image_link', models.ImageField(upload_to=images.models.user_dir_path)),
                ('expiring_link', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
