# Generated by Django 3.2.6 on 2023-02-15 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Basic', max_length=100)),
                ('image_link', models.BooleanField(default=False)),
                ('thumbnail_small', models.BooleanField(default=True)),
                ('thumbnail_large', models.BooleanField(default=True)),
                ('expiring_link', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_link',
        ),
        migrations.AddField(
            model_name='image',
            name='expiring_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_large',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_small',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
