# Generated by Django 3.2.6 on 2023-02-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('basic', 'To get basic pic'), ('premium', 'To get bigger pic'), ('enterprise', 'To get pic and link'), ('custom', 'Custom'))},
        ),
    ]
