# Generated by Django 3.2.6 on 2023-02-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(default='Basic', max_length=100),
        ),
    ]
